{% extends "base.phtml" %}
{% load core_extras %}

{% block content %}

    <div class="col-md-12">
      <div class="row">
        <h2>{{ orgao.sigla }}<br> <small>{{ orgao.descricao|title }}</small></h2>
        <h5><strong>Tipo:</strong> {{ orgao.tipo.descricao }}</h5>
      </div>

      <div class="row top-buffer">
        <p class="text-muted"></p>
      </div> 

    </div>

    <div class="col-md-12">

    <div class="row">
        <h3>Presidência</h3>
    </div>
    <div class="row">
    {% for cargoorgao in orgao.membros %}

        <div class="col-md-2">
        <img src="{{ cargoorgao.parlamentar.foto_principal }}" alt="{{ cargoorgao.parlamentar.nome_parlamentar }}" class="img-thumbnail">
        <p>{{ cargoorgao.cargo.descricao }}<BR>
        <a href="{% url "deputado" cargoorgao.parlamentar.ide_cadastro %}">{{ cargoorgao.parlamentar.nome_parlamentar }} ({{ cargoorgao.parlamentar.partido.sigla }})</a></p>
        </div>
    {% endfor %}

    </div>
    </div>

{% endblock %}
