{% extends "base.phtml" %}
{% load core_extras %}

{% block content %}

  {% if deputado %}
    <div class="col-md-9">

      <div class="row">
        <h2>{{ deputado.tratamento }} {{ deputado.nome_parlamentar|title }} <small>{{ deputado.partido.sigla }}-{{ deputado.uf }} <img src="{{ deputado.flag_uf }}" width="48px"><br>
        {{ deputado.profissao|short_job|title }}, {{deputado.idade}} Anos</small></h2>
        {% for photo in deputado.fotos_perfil %}
          <img src="{{ photo }}" style="height:110px;">
        {% endfor %}
      </div>

      <div class="row top-buffer">
        <p class="text-muted">{{ deputado.sumario|truncatechars:600 }}*
        <a href="{{ deputado.wikipedia }}">Leia mais.</a><br><small>* Texto retirado da Wikipedia e imagens retiradas do Google.</small></p>
      </div> 

    </div>

    <div class="col-md-3">
      <table class="table table-condensed top-buffer">
        <tr>
          <td><small><span class="fa fa-phone fa-fw"></span> Telefone</small></td>
          <td><small><span class="pull-right">{{ deputado.telefone }}</small></span></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-fax fa-fw"></span> Fax</small></td>
          <td><small><span class="pull-right">{{ deputado.fax }}</span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-envelope fa-fw"></span> Email</small></td>
          <td><small><span class="pull-right"><a href="mailto:{{ deputado.email }}">{{ deputado.email|truncatechars:15 }}</a></span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-cloud fa-fw"></span> Site</small></td>
          <td><small><span class="pull-right"><a href="{{ deputado.site }}">{{ deputado.site }}</a></span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-graduation-cap fa-fw"></span> Wikipedia</small></td>
          <td><small><span class="pull-right"><a href="{{ deputado.wikipedia }}">{{ deputado.wikipedia|truncatechars:20 }}</span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-facebook fa-fw"></span> Facebook</small></td>
          <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-twitter fa-fw"></span> Twitter</small></td>
          <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
        </tr>
        <tr>
          <td><small><span class="fa fa-linkedin fa-fw"></span> Linkedin</small></td>
          <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
        </tr>
        {% if deputado.endereco %} 
        <tr>
          <td colspan=2><small><strong>Endereço:</strong> {{ deputado.endereco }}</small></td>
        </tr>
        {% endif %} 
      </table>

    </div>


    <div class="col-md-12">

      <ul class="nav nav-pills">
        <li class="active"><a href="#exercicios" data-toggle="tab">Exercícios na Câmara <span class="label label-info">{{ exercicios.count }}</span></a></li>
        <li><a href="#comissoes" data-toggle="tab">Comissões <span class="label label-info">{{ deputado.comissoes_atuais.count }}</span></a></li>
        <li><a href="#proposicoes" data-toggle="tab">Proposições <span class="label label-info">{{ deputado.proposicao_set.all.count }}</span></a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane fade in active" id="exercicios">{% include "camara/deputados/exercicios.phtml" %}</div>
        <div class="tab-pane fade" id="comissoes">{% include "camara/deputados/comissoes.phtml" %}</div>
        <div class="tab-pane fade" id="proposicoes">{% include "camara/deputados/proposicoes.phtml" %}</div>
      </div>

    </div>
  {% else %}
    <p>Deputado não encontrado.</p>
  {% endif %}

{% endblock %}
