{% extends "base.phtml" %}
{% load core_extras %}

{% block content %}

  {% if deputado %}
    
    <!-- Foto e contatos -->
    <div class="row col-lg-3">

       <div class="text-center">
         <img src="{{ deputado.url_foto }}" class="img-thumbnail">
       </div>

       <div class="row center-block">
         <table class="table table-condensed top-buffer">
             <tr>
                 <td><small><span class="fa fa-phone"></span> Telefone</small></td>
                 <td><small><span class="pull-right">{{ deputado.telefone }}</small></span></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-fax"></span> Fax</small></td>
                 <td><small><span class="pull-right">{{ deputado.fax }}</span></small></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-cloud"></span> Site</small></td>
                 <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-graduation-cap"></span> Wikipedia</small></td>
                 <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-facebook"></span> Facebook</small></td>
                 <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-twitter"></span> Twitter</small></td>
                 <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
             </tr>
             <tr>
                 <td><small><span class="fa fa-linkedin"></span> Linkedin</small></td>
                 <td><small><span class="pull-right">{{ deputado.email|truncatechars:15 }}</span></small></td>
             </tr>
             {% if deputado.endereco %}
             <tr>
                 <td colspan=2><small>{{ deputado.endereco }}</small></td>
             </tr>
             {% endif %}
         </table>
      </div>
    </div>

    <!-- Resumo e estatísticas -->
    <div class="row col-lg-9">

      <div class="row">
        <div class="col-lg-9">
              <h4><strong>{{ deputado.nome|title }}</strong> <small><span class="label label-{{deputado.condicao|condicao_class}}">{{ deputado.condicao|condicao}}</span> {{ deputado.partido.sigla }}</small></h4>

            <p class="text-muted"><small>t is a useful package that contains PSD+HTML/CSS of the all controls
               designed based on latest Twitter bootstrap 3 a flat look to the user interface
               elements. There are no gradients, shadows, or rounded corners - everything looks
               clean and simple. The package will be especially useful for programmers who do
               not want to waste time & budget on custom design but still require trendy style
               to their products. Also it can be useful for everyone who requires flat design
               for their product based on easy-to-use bootstrap 3 code.</small></p>
        </div>

        <div class="col-lg-3">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">Estatísticas</h4>
              </div>
              <div class="panel-body">
                Panel content
              </div>
            </div>
        </div>
      </div>

      <div class="row">
        
      </div>

    </div>

  {% else %}
    <p>Deputado não encontrado.</p>
  {% endif %}

{% endblock %}
